name = "imgbed"
compatibility_date = "2024-04-01"
pages_build_output_dir = "./"

# 绑定kv
[[kv_namespaces]]
binding = "img_url"
id = "1d29f1b8f37c4bf59adfeec6fb9f01cf"

# R2 绑定
[[r2_buckets]]
binding = "img_r2"
bucket_name = "img-r2-bucket"
