name: Upstream Sync

permissions:
  contents: write
  actions: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:

      - name: Checkout target repo
        uses: actions/checkout@v6
        # 使用PAT来提高权限，同步工作流下的文件
        with:
          token: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}

      - name: Check sync token
        run: |
          if [ -z "${{ secrets.UPDATESTREAM_SYNC_TOKEN }}" ]; then
            echo "UPDATESTREAM_SYNC_TOKEN is empty"
            exit 1
          else
            echo "UPDATESTREAM_SYNC_TOKEN exists"
          fi

      - name: Sync upstream changes
        id: sync
        uses: aormsby/fork-sync-with-upstream-action@v3.4.3
        env:
          GH_TOKEN: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}
        with:
          upstream_sync_repo: MarSeventh/CloudFlare-ImgBed
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.UPDATESTREAM_SYNC_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "Sync failed"
          exit 1
